### ISSUE TITLE
Logo Design Questions

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/resources#18]
@plastelina, you shared a really good resource for figuring out what kind of design guidelines / logo an organization might want. Do you mind if I add that here as a link? Or maybe in a format that isn't a pdf?

**Comment by plastelina** [comment]
@simonv3 absolutely! go for it. :)

**Comment by simonv3** [comment]
@plastelina I don't remember where you shared this, do you remember?

**Comment by bnvk** [comment]
@plastelina feel free to comment here (if you want to share the guidelines Simon asked for) but closing this for tidy things up!
