### ISSUE TITLE
Common Conversations Designers have with Developers

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/resources#19]
Recently we've noted a series of common conversations that designers have to have with developers (and vice-versa) over and over again. It'd be great if we could document these all and add a variety of sources and links to this.

Here's a starting point:

http://piratepad.net/opensourcedesign-commonfossconversations

You can add topics here, or on there, alongside your views. 

> Statement 1: The Command Line is better than the GUI
> Ask Question: Better for Doing What/Whom?
> E.g. it is great for automatization, many admin tasks, using almost any unix…
> Closer to the command/execution model (how much this is actually essential in computing technology, I dont know) btw. assembler is even closer to the computer…
> bad for: (almost anything else…) anything visual, hard on the memory (pull the science card!), error prone (dd  hhd deletion via accidental parameter swap, anyone?)
> 
> Statement 2: More options to suit the developer's tastes
> Remark: Having options does not hurt (if the pro settings are reasonable designed and do not clutter e.g.  via about: config) but 1) not having good defaults hurts 2) if the most commonly needed settings drown in the other 90%.
> 
> Statement 3: Everyone has an <x> account (where x is most likely github)
> That is hard… »No, many don’t« probably. 
> Or: Yes, the ones we/you work with now, do, but what about the rest you never work with?

We can then also start compiling these as a list of resources for people. 

@jdittrich @bnvk

**Comment by jancborchardt** [comment]
Right, nice! :) A bunch of old notes I wanted to compile back then are at https://gist.github.com/jancborchardt/5967457 – regarding settings, and autosave.

Undo over confirmation modal is also a topic which comes up all the time …
Relevant article I link very often is [Aza Raskin: Never use a warning when you mean undo](http://alistapart.com/article/neveruseawarning) and a typical example discussion: https://github.com/k9mail/k-9/issues/624

**Comment by simonv3** [comment]
@jancborchardt these are great. Do you mind if I incorporate your gist notes into the document?

**Comment by jancborchardt** [comment]
@simonv3 please do, I never got around to working them into a proper doc myself. :)

**Comment by simonv3** [comment]
Closing this and moving it here: https://discourse.opensourcedesign.net/t/common-conversations-designers-have-with-developers/315
