### ISSUE TITLE
Tools We'd Like To See

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/resources#20]
Inspired by the things that @jdittrich has been talking about [here](http://piratepad.net/opensourceMockupTool), here might be a good place to list web tools we'd like to see good open source alternatives for.
- An open source style pinterest, or something similar to create a mood board and gather design inspirations - [pinry](https://github.com/pinry/pinry/) is an option, but is starting to look pretty stale and insecure.
- A/B Testing
- A pencil alternative. An UX tool that has user experience designers in mind to create low-fi wireframes and user interactions. I love this as an abstract reference on how a non design-intrusive UX could be: https://github.com/ipselon/react-ui-builder (proposed by @Xaviju)
- An open source tool for design annotations and exchange, like Zurb Notable (proposed by @jdittrich)

If you add something, I'll add it to the list. If you know of something, I'll edit the list (and also the actual readme.md).

**Comment by Xaviju** [comment]
I would love to see:
* A _pencil_ alternative. An UX tool that has user experience designers in mind to create low-fi wireframes and user interactions. I love this as an abstract reference on how a non design-intrusive UX could be: https://github.com/ipselon/react-ui-builder

**Comment by jdittrich** [comment]
An open source tool for design annotations and exchange, like [Zurb Notable](http://zurb.com/notable/features/annotations)

**Comment by nicknikolov** [comment]
https://github.com/vorg/kollektor is a pretty good Pinterest alternative. It's maintained and used by the author so don't be afraid to try and spam him with issues, its a nice project that could use more activity :)

**Comment by bnvk** [comment]
@nicknikolov that looks great. I tried it out on my local
machine- got it running easily enough. Seemed slightly glitchy,
but definitely worth using & contributing to IMHO to remove the
glitches :)

**Comment by simonv3** [comment]
That looks awesome. Let's add that to the resources list!

**Comment by RichardLitt** [comment]
I would like to see a FLOSS resource for generating images of database schemas which are platform agnostic, for planning a database before creating it.

**Comment by simonv3** [comment]
@RichardLitt something like: https://www.mysql.com/products/workbench/?

**Comment by RichardLitt** [comment]
Yes.

**Comment by simonv3** [comment]
I'm closing this and moving it to the forum: https://discourse.opensourcedesign.net/t/tools-wed-like-to-see/314
