### ISSUE TITLE
Mozilla Community Design - Call for Designers

### ISSUE THREAD

**Issue by elioqoshi** [opensourcedesign/resources#21]
Hi guys! I'm posting this here too, in case anyone is interested ( @jdittrich should be at least).

At Mozilla, as part of the goals for 2016, we will be trying to tie the volunteers involved in design contribution areas, with the Creative Team at Mozilla. We hope to raise participation with this and offer clear contribution paths to upcoming design contributors.
Fill out this form if you are interested to be part of the discussion.

For more infos, check out the GitHub issue:
https://github.com/mozilla/participation-org/issues/233

This will result in the first meeting of the Community Design Group with design staff and design contributors in January. 

Here is the sign up form (sorry for using Google Forms)
https://docs.google.com/forms/d/1Tw3Mw_CMiqcIQrJF7TB1yIETGYec__NiVhaSz0CAaE8/viewform

Let me know if you have any questions!

**Comment by bnvk** [comment]
Closing this as it never was used and we're in 2017 now :wink: @elioqoshi if Mozilla wants people from OSD community, perhaps some other outreach / effort could happen later and in a different way?!

**Comment by elioqoshi** [comment]
Yeah, I will start my contract next month @bnvk and I can facilitate that, so going back there of course
