### ISSUE TITLE
List of Free Fonts

### ISSUE THREAD

**Issue by elioqoshi** [opensourcedesign/resources#30]
Hey guys,

I stumbled uponm this listicle today which lists free (as in free beer) fonts for use for anything personal or commercial: http://www.designyourway.net/blog/resources/best-free-fonts-for-logos-72-modern-and-creative-typefaces/

Many of the fonts here are licensed under a SIL Open Font License, Apache or CC-BY-SA license, so I think that would be a great resource for Open Source Designers

**Comment by subshrijit** [comment]
Also check out http://ospublish.constantvzw.org/foundry/ if you're interested in open source fonts.

**Comment by bnvk** [comment]
@subshrijit @elioqoshi these things are great. Can you add these to the list
of items instead of just comments here?

**Comment by jancborchardt** [comment]
@elioqoshi @subshrijit as Brennan said, just add them to the list at https://github.com/opensourcedesign/resources#fonts – you can even do so with the Github online editor. :)

Also feel free to invite the typeface authors to our Github organization here, or our [Discourse forum](https://discourse.opensourcedesign.net/). :)

Closing this hence.
